// The wire contract between Clave's server and its terminal process (ADR
// 0003, wave 3): the Terminals port of `packages/server/src/terminals/port.ts`
// as gRPC, served by the Node process that owns node-pty
// (`src/main/terminal-process/`) and called by the Bun server's adapter
// (`../grpc.ts`). Field numbers are stable: add, never renumber; reserve a
// deleted number and its name.
//
// A terminal's life is apart from any one call. Spawn, Write, Resize, Kill
// and Ping are unary; Attach is one server stream per terminal carrying the
// output and the exit with a sequence number, re-opened by the caller with
// the last sequence it saw when the stream's deadline ends (the framework
// caps every call at 24 hours and a terminal may live longer). The process
// keeps the recent output of every terminal so a re-attach loses nothing,
// and kills a terminal that nobody has attached to for a grace period, so
// a server that is gone leaves nothing running.

// @generated by protoc-gen-es v2.16.0 with parameter "target=ts"
// @generated from file terminals.proto (package clave.terminals.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file terminals.proto.
 */
export const file_terminals: GenFile = /*@__PURE__*/
  fileDesc("Cg90ZXJtaW5hbHMucHJvdG8SEmNsYXZlLnRlcm1pbmFscy52MSINCgtQaW5nUmVxdWVzdCIhCgxQaW5nUmVzcG9uc2USEQoJdGVybWluYWxzGAEgASgNIsUBCgxTcGF3blJlcXVlc3QSDAoEZmlsZRgBIAEoCRIMCgRhcmdzGAIgAygJEgsKA2N3ZBgDIAEoCRI2CgNlbnYYBCADKAsyKS5jbGF2ZS50ZXJtaW5hbHMudjEuU3Bhd25SZXF1ZXN0LkVudkVudHJ5EgwKBGNvbHMYBSABKA0SDAoEcm93cxgGIAEoDRIMCgRuYW1lGAcgASgJGioKCEVudkVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiKAoNU3Bhd25SZXNwb25zZRIKCgJpZBgBIAEoCRILCgNwaWQYAiABKA0iKAoMV3JpdGVSZXF1ZXN0EgoKAmlkGAEgASgJEgwKBGRhdGEYAiABKAkiDwoNV3JpdGVSZXNwb25zZSI3Cg1SZXNpemVSZXF1ZXN0EgoKAmlkGAEgASgJEgwKBGNvbHMYAiABKA0SDAoEcm93cxgDIAEoDSIQCg5SZXNpemVSZXNwb25zZSIpCgtLaWxsUmVxdWVzdBIKCgJpZBgBIAEoCRIOCgZzaWduYWwYAiABKAkiDgoMS2lsbFJlc3BvbnNlIioKDUF0dGFjaFJlcXVlc3QSCgoCaWQYASABKAkSDQoFYWZ0ZXIYAiABKAQiqQEKDVRlcm1pbmFsRXZlbnQSCwoDc2VxGAEgASgEEiwKBm91dHB1dBgCIAEoCzIaLmNsYXZlLnRlcm1pbmFscy52MS5PdXRwdXRIABIsCgZleGl0ZWQYAyABKAsyGi5jbGF2ZS50ZXJtaW5hbHMudjEuRXhpdGVkSAASJgoDZ2FwGAQgASgLMhcuY2xhdmUudGVybWluYWxzLnYxLkdhcEgAQgcKBWV2ZW50IhYKBk91dHB1dBIMCgRkYXRhGAEgASgJIjsKBkV4aXRlZBIRCglleGl0X2NvZGUYASABKAUSEwoGc2lnbmFsGAIgASgFSACIAQFCCQoHX3NpZ25hbCITCgNHYXASDAoEbG9zdBgBIAEoBCIeCgxTcGF3blJlZnVzZWQSDgoGcmVhc29uGAEgASgJIh0KD1Vua25vd25UZXJtaW5hbBIKCgJpZBgBIAEoCTLgAwoJVGVybWluYWxzEkkKBFBpbmcSHy5jbGF2ZS50ZXJtaW5hbHMudjEuUGluZ1JlcXVlc3QaIC5jbGF2ZS50ZXJtaW5hbHMudjEuUGluZ1Jlc3BvbnNlEkwKBVNwYXduEiAuY2xhdmUudGVybWluYWxzLnYxLlNwYXduUmVxdWVzdBohLmNsYXZlLnRlcm1pbmFscy52MS5TcGF3blJlc3BvbnNlEkwKBVdyaXRlEiAuY2xhdmUudGVybWluYWxzLnYxLldyaXRlUmVxdWVzdBohLmNsYXZlLnRlcm1pbmFscy52MS5Xcml0ZVJlc3BvbnNlEk8KBlJlc2l6ZRIhLmNsYXZlLnRlcm1pbmFscy52MS5SZXNpemVSZXF1ZXN0GiIuY2xhdmUudGVybWluYWxzLnYxLlJlc2l6ZVJlc3BvbnNlEkkKBEtpbGwSHy5jbGF2ZS50ZXJtaW5hbHMudjEuS2lsbFJlcXVlc3QaIC5jbGF2ZS50ZXJtaW5hbHMudjEuS2lsbFJlc3BvbnNlElAKBkF0dGFjaBIhLmNsYXZlLnRlcm1pbmFscy52MS5BdHRhY2hSZXF1ZXN0GiEuY2xhdmUudGVybWluYWxzLnYxLlRlcm1pbmFsRXZlbnQwAWIGcHJvdG8z");

/**
 * @generated from message clave.terminals.v1.PingRequest
 */
export type PingRequest = Message<"clave.terminals.v1.PingRequest"> & {
};

/**
 * Describes the message clave.terminals.v1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_terminals, 0);

/**
 * @generated from message clave.terminals.v1.PingResponse
 */
export type PingResponse = Message<"clave.terminals.v1.PingResponse"> & {
  /**
   * @generated from field: uint32 terminals = 1;
   */
  terminals: number;
};

/**
 * Describes the message clave.terminals.v1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_terminals, 1);

/**
 * @generated from message clave.terminals.v1.SpawnRequest
 */
export type SpawnRequest = Message<"clave.terminals.v1.SpawnRequest"> & {
  /**
   * @generated from field: string file = 1;
   */
  file: string;

  /**
   * @generated from field: repeated string args = 2;
   */
  args: string[];

  /**
   * @generated from field: string cwd = 3;
   */
  cwd: string;

  /**
   * @generated from field: map<string, string> env = 4;
   */
  env: { [key: string]: string };

  /**
   * @generated from field: uint32 cols = 5;
   */
  cols: number;

  /**
   * @generated from field: uint32 rows = 6;
   */
  rows: number;

  /**
   * The terminal name advertised to the process (`xterm-256color`); the
   * library's default when empty.
   *
   * @generated from field: string name = 7;
   */
  name: string;
};

/**
 * Describes the message clave.terminals.v1.SpawnRequest.
 * Use `create(SpawnRequestSchema)` to create a new message.
 */
export const SpawnRequestSchema: GenMessage<SpawnRequest> = /*@__PURE__*/
  messageDesc(file_terminals, 2);

/**
 * @generated from message clave.terminals.v1.SpawnResponse
 */
export type SpawnResponse = Message<"clave.terminals.v1.SpawnResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: uint32 pid = 2;
   */
  pid: number;
};

/**
 * Describes the message clave.terminals.v1.SpawnResponse.
 * Use `create(SpawnResponseSchema)` to create a new message.
 */
export const SpawnResponseSchema: GenMessage<SpawnResponse> = /*@__PURE__*/
  messageDesc(file_terminals, 3);

/**
 * @generated from message clave.terminals.v1.WriteRequest
 */
export type WriteRequest = Message<"clave.terminals.v1.WriteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string data = 2;
   */
  data: string;
};

/**
 * Describes the message clave.terminals.v1.WriteRequest.
 * Use `create(WriteRequestSchema)` to create a new message.
 */
export const WriteRequestSchema: GenMessage<WriteRequest> = /*@__PURE__*/
  messageDesc(file_terminals, 4);

/**
 * @generated from message clave.terminals.v1.WriteResponse
 */
export type WriteResponse = Message<"clave.terminals.v1.WriteResponse"> & {
};

/**
 * Describes the message clave.terminals.v1.WriteResponse.
 * Use `create(WriteResponseSchema)` to create a new message.
 */
export const WriteResponseSchema: GenMessage<WriteResponse> = /*@__PURE__*/
  messageDesc(file_terminals, 5);

/**
 * @generated from message clave.terminals.v1.ResizeRequest
 */
export type ResizeRequest = Message<"clave.terminals.v1.ResizeRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: uint32 cols = 2;
   */
  cols: number;

  /**
   * @generated from field: uint32 rows = 3;
   */
  rows: number;
};

/**
 * Describes the message clave.terminals.v1.ResizeRequest.
 * Use `create(ResizeRequestSchema)` to create a new message.
 */
export const ResizeRequestSchema: GenMessage<ResizeRequest> = /*@__PURE__*/
  messageDesc(file_terminals, 6);

/**
 * @generated from message clave.terminals.v1.ResizeResponse
 */
export type ResizeResponse = Message<"clave.terminals.v1.ResizeResponse"> & {
};

/**
 * Describes the message clave.terminals.v1.ResizeResponse.
 * Use `create(ResizeResponseSchema)` to create a new message.
 */
export const ResizeResponseSchema: GenMessage<ResizeResponse> = /*@__PURE__*/
  messageDesc(file_terminals, 7);

/**
 * @generated from message clave.terminals.v1.KillRequest
 */
export type KillRequest = Message<"clave.terminals.v1.KillRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string signal = 2;
   */
  signal: string;
};

/**
 * Describes the message clave.terminals.v1.KillRequest.
 * Use `create(KillRequestSchema)` to create a new message.
 */
export const KillRequestSchema: GenMessage<KillRequest> = /*@__PURE__*/
  messageDesc(file_terminals, 8);

/**
 * @generated from message clave.terminals.v1.KillResponse
 */
export type KillResponse = Message<"clave.terminals.v1.KillResponse"> & {
};

/**
 * Describes the message clave.terminals.v1.KillResponse.
 * Use `create(KillResponseSchema)` to create a new message.
 */
export const KillResponseSchema: GenMessage<KillResponse> = /*@__PURE__*/
  messageDesc(file_terminals, 9);

/**
 * @generated from message clave.terminals.v1.AttachRequest
 */
export type AttachRequest = Message<"clave.terminals.v1.AttachRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: uint64 after = 2;
   */
  after: bigint;
};

/**
 * Describes the message clave.terminals.v1.AttachRequest.
 * Use `create(AttachRequestSchema)` to create a new message.
 */
export const AttachRequestSchema: GenMessage<AttachRequest> = /*@__PURE__*/
  messageDesc(file_terminals, 10);

/**
 * @generated from message clave.terminals.v1.TerminalEvent
 */
export type TerminalEvent = Message<"clave.terminals.v1.TerminalEvent"> & {
  /**
   * @generated from field: uint64 seq = 1;
   */
  seq: bigint;

  /**
   * @generated from oneof clave.terminals.v1.TerminalEvent.event
   */
  event: {
    /**
     * @generated from field: clave.terminals.v1.Output output = 2;
     */
    value: Output;
    case: "output";
  } | {
    /**
     * @generated from field: clave.terminals.v1.Exited exited = 3;
     */
    value: Exited;
    case: "exited";
  } | {
    /**
     * @generated from field: clave.terminals.v1.Gap gap = 4;
     */
    value: Gap;
    case: "gap";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message clave.terminals.v1.TerminalEvent.
 * Use `create(TerminalEventSchema)` to create a new message.
 */
export const TerminalEventSchema: GenMessage<TerminalEvent> = /*@__PURE__*/
  messageDesc(file_terminals, 11);

/**
 * @generated from message clave.terminals.v1.Output
 */
export type Output = Message<"clave.terminals.v1.Output"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message clave.terminals.v1.Output.
 * Use `create(OutputSchema)` to create a new message.
 */
export const OutputSchema: GenMessage<Output> = /*@__PURE__*/
  messageDesc(file_terminals, 12);

/**
 * @generated from message clave.terminals.v1.Exited
 */
export type Exited = Message<"clave.terminals.v1.Exited"> & {
  /**
   * @generated from field: int32 exit_code = 1;
   */
  exitCode: number;

  /**
   * @generated from field: optional int32 signal = 2;
   */
  signal?: number | undefined;
};

/**
 * Describes the message clave.terminals.v1.Exited.
 * Use `create(ExitedSchema)` to create a new message.
 */
export const ExitedSchema: GenMessage<Exited> = /*@__PURE__*/
  messageDesc(file_terminals, 13);

/**
 * Output the process no longer holds: the caller asked for a sequence older
 * than what is kept. `lost` events are missing before the next Output.
 *
 * @generated from message clave.terminals.v1.Gap
 */
export type Gap = Message<"clave.terminals.v1.Gap"> & {
  /**
   * @generated from field: uint64 lost = 1;
   */
  lost: bigint;
};

/**
 * Describes the message clave.terminals.v1.Gap.
 * Use `create(GapSchema)` to create a new message.
 */
export const GapSchema: GenMessage<Gap> = /*@__PURE__*/
  messageDesc(file_terminals, 14);

/**
 * The declared failures, carried as the framework's business failures.
 *
 * @generated from message clave.terminals.v1.SpawnRefused
 */
export type SpawnRefused = Message<"clave.terminals.v1.SpawnRefused"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;
};

/**
 * Describes the message clave.terminals.v1.SpawnRefused.
 * Use `create(SpawnRefusedSchema)` to create a new message.
 */
export const SpawnRefusedSchema: GenMessage<SpawnRefused> = /*@__PURE__*/
  messageDesc(file_terminals, 15);

/**
 * @generated from message clave.terminals.v1.UnknownTerminal
 */
export type UnknownTerminal = Message<"clave.terminals.v1.UnknownTerminal"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message clave.terminals.v1.UnknownTerminal.
 * Use `create(UnknownTerminalSchema)` to create a new message.
 */
export const UnknownTerminalSchema: GenMessage<UnknownTerminal> = /*@__PURE__*/
  messageDesc(file_terminals, 16);

/**
 * @generated from service clave.terminals.v1.Terminals
 */
export const Terminals: GenService<{
  /**
   * Says the process answers, and how many terminals it holds.
   *
   * @generated from rpc clave.terminals.v1.Terminals.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
  /**
   * Starts a process on a pseudo-terminal. Fails with SpawnRefused when the
   * spawn itself fails (a directory that does not exist, a file that cannot
   * run), with the reason.
   *
   * @generated from rpc clave.terminals.v1.Terminals.Spawn
   */
  spawn: {
    methodKind: "unary";
    input: typeof SpawnRequestSchema;
    output: typeof SpawnResponseSchema;
  },
  /**
   * Writes to the terminal's input. Fails with UnknownTerminal.
   *
   * @generated from rpc clave.terminals.v1.Terminals.Write
   */
  write: {
    methodKind: "unary";
    input: typeof WriteRequestSchema;
    output: typeof WriteResponseSchema;
  },
  /**
   * Resizes the terminal. Fails with UnknownTerminal.
   *
   * @generated from rpc clave.terminals.v1.Terminals.Resize
   */
  resize: {
    methodKind: "unary";
    input: typeof ResizeRequestSchema;
    output: typeof ResizeResponseSchema;
  },
  /**
   * Sends a signal to the process (SIGHUP when none is named). Fails with
   * UnknownTerminal.
   *
   * @generated from rpc clave.terminals.v1.Terminals.Kill
   */
  kill: {
    methodKind: "unary";
    input: typeof KillRequestSchema;
    output: typeof KillResponseSchema;
  },
  /**
   * Streams the terminal's events from the sequence after `after` (0 for all
   * the process still holds), then as they happen, ending after Exited.
   * Fails with UnknownTerminal.
   *
   * @generated from rpc clave.terminals.v1.Terminals.Attach
   */
  attach: {
    methodKind: "server_streaming";
    input: typeof AttachRequestSchema;
    output: typeof TerminalEventSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_terminals, 0);

